### PR TITLE
Fix redirection and file path handling for URL with query strings

### LINKED ISSUE #110: `LiveServer.serve` redirects /page/?query=string to /page/?query=string/
MWE:

```julia
using LiveServer
mktempdir() do path
    cd(path) do
        mkpath("a/b")
        write("a/b/index.html", "hello")
        serve()
    end
end
```

Then accessing http://localhost:8000/a/b/?c=d is redirected to http://localhost:8000/a/b/?c=d/ (note the `/` at the end). There is no redirection with http://localhost:8000/a/b/index.html?c=d.

I checked this with the current latest release v0.5.6.

(ref https://github.com/tlienart/Franklin.jl/issues/641)

### PR DESCRIPTION
**Pull request by tkf**
This PR closes #110

Changes:

* `/a/b?c=d` is redirected to `/a/b/?c=d`
* `/a/b/?c=d` serves `/a/b/index.html`

### CODE REVIEW

File: src/server.jl [hunk 1]
```diff
@@ -77,14 +77,15 @@ Return the filesystem path corresponding to a requested path, or an empty
...
     # first element after the split is **always** "/"
-    r_parts = HTTP.URIs.unescapeuri.(split(HTTP.URI(req_path).path[2:end], "/"))
+    r_parts = HTTP.URIs.unescapeuri.(split(uri.path[2:end], "/"))
     fs_path = joinpath(r_parts...)
     if !isempty(CONTENT_DIR[])
         fs_path = joinpath(CONTENT_DIR[], fs_path)
     end
     # if no file is specified, try to append `index.html` and see
-    endswith(req_path, "/") && (fs_path = joinpath(fs_path, "index.html"))
+    endswith(uri.path, "/") && (fs_path = joinpath(fs_path, "index.html"))
```
Comment (tkf) [inline src/server.jl:88]: @fredrikekre Thanks for the pointer! https://github.com/tlienart/Franklin.jl/issues/641#issuecomment-703473341

**Comment by tlienart** [comment]
Thanks a lot! I'll look into how you tackled this a bit later and will merge 🙌🏼
